### ISSUE TITLE
[Chore] Improve route naming

### ISSUE THREAD

**Issue by olivierobert** [AetheryNA/google-scraper#55]
## Issue

The application routes do not follow standard naming and can be simplified:

- `results/view-html?keywordName=project&keywordID=:keyword-id` could be `results/:keyword-id/html`. Use query params for GET requests initiated by a form e.g., search
- `/results/search-keywords?keywordToSearch=app` could be `/results?keyword=app`
- `/dashboard/upload-file-and-scrape-data` could `/dashboard/upload`

While variable naming requires being more descriptive, routes should be simpler and follow standard and battle-tested patterns. While not JS-centric, the patterns used in Ruby on Rails are conventional: https://guides.rubyonrails.org/routing.html

**Comment by AetheryNA** [comment]
Thanks for the suggestion and the resources for routing! 😸 

I've implemented the suggestion that you've made, you can find it here #59. On a side note the first suggestion; I've named the route `results/:keyword_id/view-html` instead of just `html` because I feel that `view-html` is simple enough to fit naming standards and the reason as to why I would like it this way is that it sounds more literal when saying `view-html` as in the user will see a rendered html. 🤔 

What are your thoughts on this? If you disagree I'd be glad to fix it in another PR 😸

**Comment by olivierobert** [comment]
Being a GET request, the prefix `view-` seems a bit redundant but it is not a blocker to keep it 😁
